package com.tien.common.exception;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@AllArgsConstructor
@Getter
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public enum ErrorCode {
    /** explain codes
     * key cloak: 1
     * crud user error: 9
     * DB: 5
     * excel: 7
     */
    USER_NOT_FOUND(1, "USER NOT FOUND", HttpStatus.NOT_FOUND),
    PASS_INCORRECT(0, "PASSWORD INCORRECT", HttpStatus.BAD_REQUEST),
    ERROR_TOKEN(6, "TOKEN ERROR", HttpStatus.UNAUTHORIZED),
    ERROR_PUBLIC_ID(7, "NOT FOUND PUBLIC ID IN DATABASE", HttpStatus.INTERNAL_SERVER_ERROR),
    UPLOAD_A_FILE_ERROR(7, "UPLOAD FILE FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    UNKNOW_ERROR(3, "UNKNOWN ERROR", HttpStatus.INTERNAL_SERVER_ERROR), //500
    NAME_EXIST(2, "NAME EXISTED", HttpStatus.BAD_REQUEST),
    ACCESS_DENIED(4, "ACCESS DENIED", HttpStatus.FORBIDDEN),
    UNAUTHENTICATED(5, "USER NOT AUTHENTICATED", HttpStatus.UNAUTHORIZED),
    INVALID_OTP(0, "OTP INVALID", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(0, "EMAIL INVALID", HttpStatus.BAD_REQUEST),
    INVALID_LOGIN(0, "INVALID EMAIL OR PASSWORD", HttpStatus.BAD_REQUEST),
    EXPIRED_TOKEN(6, "TOKEN IS EXPIRED", HttpStatus.BAD_REQUEST),
    UNVERIFY_TOKEN(6, "TOKEN IS NOT VERIFIED", HttpStatus.BAD_REQUEST),
    ERROR_UPLOAD_FILE(7, "ERROR UPLOAD FILE", HttpStatus.INTERNAL_SERVER_ERROR),
    ERROR_DELETE_FILE(7, "DELETE FILE FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ERROR_UPDATE_FILE(7, "UPDATE FILE FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ERROR_STRING_CONVERT_INSTANT(8, "STRING CONVERT TO INSTANT FAILED, INPUT IS NULL", HttpStatus.BAD_REQUEST),
    NOT_MATCH_PASSWORD(0, "OLD PASSWORD AND NEW PASSWORD DO NOT MATCH", HttpStatus.BAD_REQUEST),
    ERROR_DELETE(9, "USER HAS BEEN DELETED", HttpStatus.BAD_REQUEST),
    ERROR_KEYCLOAK_USER(1, "CREATE USER IN KEYCLOAK FAILED", HttpStatus.BAD_REQUEST),
    USER_FILTER(3, "USER NOT FOUND IN DATABASE", HttpStatus.FORBIDDEN),
    ADMIN_TOKEN_NOT_FOUND(3, "ADMIN ACCESS TOKEN NOT FOUND", HttpStatus.BAD_REQUEST),
    CREATED_USER_KEYCLOAK_ERROR(1, "ERROR CREATING USER IN KEYCLOAK", HttpStatus.BAD_REQUEST),
    PERMISSION_REPOSITORY_EMPTY(5, "PERMISSION REPOSITORY IS EMPTY", HttpStatus.BAD_REQUEST),
    ROLE_REPOSITORY_EMPTY(5, "ROLE REPOSITORY IS EMPTY", HttpStatus.BAD_REQUEST),
    ERROR_EXCEL_HEADER(7, "NO HEADER IN EXCEL FILE", HttpStatus.BAD_REQUEST);

      int code;
      String message;
      HttpStatusCode httpStatusCode;
}
